<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Events\Events.csproj" />
    <ProjectReference Include="..\View\View.csproj" />
    <ProjectReference Include="..\Controllers\Controllers.csproj" />
    <ProjectReference Include="..\Debug\Debug.csproj" />
    <ProjectReference Include="..\View.Definitions\View.Definitions.csproj" />
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Events.Definitions\Events.Definitions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
