<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UserInterface\UserInterface.csproj" />
    <ProjectReference Include="..\Events\Events.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\Requests\Requests.csproj" />
    <ProjectReference Include="..\Resources\Resources.csproj" />
    <ProjectReference Include="..\View\View.csproj" />
    <ProjectReference Include="..\Controllers\Controllers.csproj" />
    <ProjectReference Include="..\View.Definitions\View.Definitions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
